rabbitmq:
  hosts:
    - host: "192.168.56.1"
      port: 5672
    - host: "192.168.50.1"
      port: 5672
  username: "myuser"
  password: "mypassword"

nodes:
  - id: "node1"
    ip: "192.168.156.101"
    port: 7071
  - id: "node2"
    ip: "192.168.156.102"
    port: 7072
  - id: "node3"
    ip: "192.168.156.103"
    port: 7073
  - id: "node4"
    ip: "192.168.156.104"
    port: 7074
  - id: "node5"
    ip: "192.168.156.105"
    port: 7075

resources:
  - "R1"
  - "R2"
  - "R3"
  - "R4"